name: Run Telegram Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install python-telegram-bot
          pip install requests
      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python main.py
